ALTER TABLE public.entreprise
ADD COLUMN IF NOT EXISTS rib TEXT,
ADD COLUMN IF NOT EXISTS banque TEXT,
ADD COLUMN IF NOT EXISTS agence TEXT,
ADD COLUMN IF NOT EXISTS rc TEXT,
ADD COLUMN IF NOT EXISTS nif TEXT,
ADD COLUMN IF NOT EXISTS nis TEXT,
ADD COLUMN IF NOT EXISTS ai TEXT;